### ISSUE TITLE
After cloning the code, the dependency was installed, but the browser cannot run

### ISSUE THREAD

**Issue by yiyuqi** [Royal-lobster/Syncia#32]
Hello brother, after I cloned the code, I installed the dependency and successfully started it. However, when the browser opened, it prompted that the webpage could not be found
![image](https://github.com/Royal-lobster/Syncia/assets/25222257/63872968-9360-4d3e-87f2-89177987ce03)

**Comment by Royal-lobster** [comment]
After building, you have to install the extension from generated dist folder. you can check this page for more info -> https://github.com/Royal-lobster/Syncia/blob/main/CONTRIBUTING.md

**Comment by yiyuqi** [comment]
I see that your plugin is quite useful, but there is also a side plugin that may look better on the UI

**Comment by yiyuqi** [comment]
> 构建后，您必须从生成的 dist 文件夹安装扩展。您可以查看此页面以获取更多信息 - > https://github.com/Royal-lobster/Syncia/blob/main/CONTRIBUTING.md

After downloading the source code, I would like to add some features or transfer to the company's own API. Is this okay

**Comment by Royal-lobster** [comment]
> > 构建后，您必须从生成的 dist 文件夹安装扩展。您可以查看此页面以获取更多信息 - > [`main`/CONTRIBUTING.md](https://github.com/Royal-lobster/Syncia/blob/main/CONTRIBUTING.md?rgh-link-date=2023-09-14T07%3A32%3A06Z)
> 
> After downloading the source code, I would like to add some features or transfer to the company's own API. Is this okay

Yes you could !
