### ISSUE TITLE
plasmo

### ISSUE THREAD

**Issue by yiyuqi** [Royal-lobster/Syncia#34]
Can we transform this project into a ### **plasmo**? This way, hot updates are supported during development

**Comment by Royal-lobster** [comment]
Wow this is new to me, i will check it out. but rn the extension development supports hmr with crxjs. i will investigate plasmo. if it gives better dx we can convert to using it 👏

**Comment by yiyuqi** [comment]
How do you currently debug locally?

**Comment by Royal-lobster** [comment]
Investigated, currently it requires a lot of work to be done, for now we would close the issue as not planned. but if anyone willing to port, feel free to reopen the issue !
