### ISSUE TITLE
Support new OpenAI API key structure

### ISSUE THREAD

**Issue by Korayem** [Royal-lobster/Syncia#66]
I generated a new API key and it's like this `sk-proj-868HDcFnu3ZjrPgk4iyFT3BlbkFJoqlINjQ2UQs1SWV9rI7t` (don't worry i deleted it)

I can't use the extension as the KEY doesnt match expected format

**Comment by Royal-lobster** [comment]
Pushed a fix for it ! should be live in 3 days once google reviews are done

**Comment by Korayem** [comment]
> Pushed a fix for it ! should be live in 3 days once google reviews are done

THANKS!!
