### ISSUE TITLE
do you have a plan to move the sidebar into the Chrome side panel

### ISSUE THREAD

**Issue by chengfengfengwang** [Royal-lobster/Syncia#71]
Hi, do you have a plan to move the sidebar into the [Chrome side panel](https://developer.chrome.com/docs/extensions/reference/api/sidePanel)? Perhaps using the side panel is a more convenient way to interact with the page.
I see the project, but the task of refactoring the project may be heavy, especially the content script quick menu part.

**Comment by Royal-lobster** [comment]
Oh yes, Read about that, i think probably we can do it as a optional setting cuz not all chromium browsers support that i believe

**Comment by Royal-lobster** [comment]
Hii, i think we are going to just stay with the current implementation we have, mainly cuz i am looking to make the interface more dynamic depending on the webpage user is in, i don't think chrome side panel api would support this vision
