### ISSUE TITLE
Chat tabs or create a way to preserve sessions of chat

### ISSUE THREAD

**Issue by Royal-lobster** [Royal-lobster/Syncia#8]
Currently only one session of chat is available to make and once the chat is cleared the chat is gone. we need a way to save the chat to a local storage and continue in a fresh "tab"

**Comment by vimal-oneway** [comment]
can I work on it

**Comment by Royal-lobster** [comment]
Oh yes ! first we need a design for it. i will work on it so you can start implementing.

**Comment by Royal-lobster** [comment]
Done with [design](https://www.figma.com/file/Wbajybrt6KtbMF1mGwDS9q/Syncia?node-id=49-548&t=pyZ8anjEmFvt1RW0-0)

![CleanShot 2023-04-23 at 00 39 58@2x](https://user-images.githubusercontent.com/52039218/233802333-ccdd0161-81f6-4c9d-ae59-6f4686556e72.png)

You can start working on the api for storing history using `useStorage`, after that we can discus about implementing the UI over with it. we need to store the site and timestamp on clear chat action.

**Comment by vimal-oneway** [comment]
okay!
can we set array index to id for history?

**Comment by vimal-oneway** [comment]
kindly re-assign me :)

**Comment by Royal-lobster** [comment]
> okay! can we set array index to id for history?

Yes. we can use [crypto.randomUUID ](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) we should be able to add and delete the history items as well

**Comment by vimal-oneway** [comment]
okay, I implemented uuid to it.
