### ISSUE TITLE
Fail to load chrome extension

### ISSUE THREAD

**Issue by alexpong0630** [Royal-lobster/Syncia#88]
The extension failed after chrome upgrade

`Refused to load the script 'chrome-extension://2c1d14fb-9c41-416a-9acc-b9ab7f203cb0/assets/sidebar.tsx-82d52c2d.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

![image](https://github.com/user-attachments/assets/0b545a15-05a4-40fa-9e08-5c06c05c1f4b)

**Comment by Royal-lobster** [comment]
Wow, i'll investigate this ASAP

**Comment by Royal-lobster** [comment]
Pushed a update, i believe 1.5.2 should fix, currently its in review

**Comment by Royal-lobster** [comment]
@alexpong0630 is it working for you now ? it does work fine for me in 1.5.2 update from chrome webstore

**Comment by alexpong0630** [comment]
@Royal-lobster it works perfect. Thanks
