### ISSUE TITLE
Error trying to do the embeddings

### ISSUE THREAD

**Issue by hdnh2006** [Royal-lobster/Syncia#95]
Hello, 

I am trying to use Syncia for translation and I am getting the following message

```
Failed to execute 'setItem' on 'Storage': Setting the value of 'SYNCIA_STORE_EMBEDDINGS_a622b46b9400436da14f4bc92f7e66bb3dcd5644a715a17836654748ed6b83f8' exceeded the quota.
``` 

It doesn't look a quota problem of my OpenAI account because the requesto to the embedding endpoint is succesfully done:
![image](https://github.com/user-attachments/assets/299d5b3d-adca-442c-a3b2-aefe43cfa91f)

There are a couple of issues in Stackoverflow related with Javascript but my knowledge is null:
https://stackoverflow.com/questions/23977690/setting-the-value-of-dataurl-exceeded-the-quota
https://stackoverflow.com/questions/71613217/failed-to-execute-setitem-on-storage-setting-the-value-of-state-exceeded

Can you please check it?

**Comment by Royal-lobster** [comment]
Hmm interesting, perhaps its related with the local storage 4mb limit. better to change it to indexed db
